version: "3"
services:
    jupyter:
        image: jupyter/scipy-notebook
        env_file:
            - ./config/jupyter.env
        ports:
            - 8888:8888
        volumes:
            - ./notebooks:/home/jovyan/work
        entrypoint: sh -c 'start-notebook.sh --NotebookApp.token=$$JUPYTER_PASSWORD'
